server:
 port: 7002
eureka:
  instance: # eureak实例定义
    hostname: eureka2 # 定义 Eureka 实例所在的主机名称
  client:
    fetch-registry: false # 是否从eureka中获取注册信息
    register-with-eureka: false #是否注册到注册中心
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
  server:
      eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间1s，而后这个时间使用的是毫秒单位（默认是60秒）
      enable-self-preservation: false #设置为false表示关闭保护模式

spring:
  security:
    user:
      name: admin
      password: admin